services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: EjerciciosDB
    environment:
      - MSSQL_SA_PASSWORD=EjerciciosDB.2024
      - ACCEPT_EULA=Y
    ports:
      - "1434:1433"
    volumes:
      - EjerciciosDB-volume:/var/opt/mssql

  seq:
    image: datalust/seq:latest
    container_name: seq_EjerciciosDB
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - seq_data_EjerciciosDB:/data

networks:
  EjerciciosDB-network:
    driver: bridge

volumes:
  EjerciciosDB-volume:
    external: true

  seq_data_EjerciciosDB:
    external: true

  seq_data:
